---
- hosts: localhost 
  connection: local
  become: true

  pre_tasks: 
  - name: update repositories
    apt:
      update_cache: yes
    changed_when: False

#  - name: update repositories
#    apt:
#      update_cache: yes
#      changed_when: False

  tasks:
  - name: Enable i386 Architecture
    command: dpkg --add-architecture i386

  - name: install packages
    package: 
      name: 
        - htop
        - remmina
        - timeshift
        - thunderbird
        - snapd 
        - python3-psutil        
        - libgl1-mesa-dri:i386
        - mesa-vulkan-drivers
        - mesa-vulkan-drivers:i386
        - wget        
        - discord
        - steam
        - openssh-server


#  - name: 250SSD Mountpoint for fstab
#    file: 
#      path: /media/250SSD
#      owner: kenny
#      group: kenny

#  - name: Drive Mountpoint for fstab
#    file:
#      path: /media/Drive
#      owner: kenny
#      group: kenny

#  - name: GameNVME Mountpoint for fstab
#    file:
#      path: /media/GameNVME
#      owner: kenny
#      group: kenny

#  - name: 1tbNVME Mountpoint for fstab
#    file:
#      path: /media/1tbNVME
#      owner: kenny
#      group: kenny

#  - name: Enable i386 Architecture
#    command: dpkg --add-architecture i386

  - name: copy wallpaper file
    copy: 
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: kenny
    dconf: 
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: kenny
    dconf: 
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy: 
      src: files/bashrc
      dest: /home/kenny/.bashrc
      owner: kenny
      group: kenny

  - name: copy environment for aco compiler
    copy: 
      src: files/environment
      dest: /etc/envirnment
      owner: root
      group: root

  - name: add ansible user
    user: 
      name: glados
      system: yes

  - name: set up sudo for ansible user
    copy: 
      src: files/sudoer_glados
      dest: /etc/sudoers.d/glados
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron: 
      name: ansible auto-provision
      user: glados
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/senpaikcarter/ansible.git
    
  - name: add repositories
    apt_repository:
      repo: ppa:kisak/kisak-mesa
  
  - name: snap install spotify
    snap:
      name: 
        - spotify

  - name: snap install vscode 
    snap: 
      name: code
      classic: yes
