---
- hosts: localhost 
  connection: local
  become: true

  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - remmina
        - timeshift
        - thunderbird
        - snapd 
        
